### ISSUE TITLE
thank you email: put image inline?

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#259]
We originally included the image as a link b/c we were doing plain text emails.  Now that we're doing HTML, we could include it inline..

@WaBirder57 your call if you think this is worth doing

**Comment by WaBirder57** [comment]
Yes, having the image inline for the emails would be preferred and worth doing.

 

Charlie

**Comment by mscholtz** [comment]
@WaBirder57 please set priority

**Comment by cguardia** [comment]
Added an image tag to the body of the email.

**Comment by WaBirder57** [comment]
Tiffany reports the following problem with this now.  Email is not sent but the following error appears: 
![wpemailthanksimageerror](https://cloud.githubusercontent.com/assets/8312206/10651676/d7ef3e36-7805-11e5-84b1-2e266cc0fbcb.PNG)

So I tried to do this as a crew leader for the following parties: 
https://cs9.salesforce.com/a2eK00000000jDN 
https://cs9.salesforce.com/a2eK00000000jDS
https://cs9.salesforce.com/a2eK00000000jDX

I tried on three different browsers, with and without a picture attached and in each case I got a message that I could not send message (see attached). No reason was given. Despite the message the WP was marked as completed in SF, with the report attached and with the box "email to crew on publish" checked so to a staff member it would look as if an email had been send. On the user side, there was no option to fix something and resend the message. 

I did clone those WPs from the same source so it's possible there's something in the SF record that is giving me the error but I can't figure out what it would be.

**Comment by davisagli** [comment]
Can you debug this @cguardia?

David Glick
(mobile)

**Comment by WaBirder57** [comment]
Did Matthew at one point say that there is some API issue regarding sending images this way using SendGrid, or was that regarding a different issue?

 

Charlie

**Comment by davisagli** [comment]
Different issue; we are just sending an img tag that loads an image from a URL here, not the image data as an attachment

David Glick
(mobile)

**Comment by cguardia** [comment]
I have not been able to reproduce this so far (email gets sent for me). However, I noticed something else: The help text for the image field says that the user can put the URL of an image or a of a page with images. Inserting an image tag will not work in the latter case. Maybe I should see if the URL ends with an image extension and use an image tag in that case, or a plain link otherwise?

**Comment by cguardia** [comment]
I did it the way I described above.

**Comment by WaBirder57** [comment]
I will ask Tiffany to send more detailed steps to reproduce the error she reported.

**Comment by WaBirder57** [comment]
@cguardia Here is more from Tiffany:

Okay, I think I've got something figured out. 

I tested this a bunch of different ways and if you want to read the details, I attached a google doc where I documented what I was doing. But the gist is: I was consistently blocked on sending a message until I edited the subject line of the email message, at which point the message sent. As long as I left the automatically generated subject line intact, it did not send. 

As for the original test, regarding inline images, that is also a little glitchy. See the attached screenshot from gmail (I also tried yahoo--same result)

![picture inline gmail](https://cloud.githubusercontent.com/assets/8312206/10680401/39441160-78d4-11e5-91f6-45ac626d9c95.PNG)

Here is a link to the Google doc with more details.
https://docs.google.com/document/d/1CCcoUzPmEQ1mBBD9fR6udvl65HTMBJGrjfh8Q21oF98/edit?usp=drive_web

**Comment by davisagli** [comment]
Thanks, that's a great clue about it not working unless you edit the subject. We'll take another look.

**Comment by cguardia** [comment]
I believe I have fixed the issues, but this is not deployed yet.

**Comment by WaBirder57** [comment]
Here is more info on this which i hope will clear up once this fix is deployed.  Report from Julie:

The image is not showing up in the thank you email. 
Here's what it looks like in the email to the participants, simply saying "Images": http://prntscr.com/8v12fh
Here's what's in the summary report: http://prntscr.com/8v12wz
Here's the actual link I entered into the summary report: https://lh3.googleusercontent.com/-LoW0MBhVN_Y/UrSBJVcLpUI/AAAAAAAAASE/jpEuUBOoJJc/w1153-h865-no/DSCN7254.JPG

**Comment by cguardia** [comment]
Right, I made the silly mistake of not making the image extension check case-independent. Fixed and should be working after next deploy.

**Comment by ebskopin** [comment]
Still doesn't see to be working.

Recent Test (1/14):
Here's what the resulting email looks like: http://prntscr.com/9q8rbt 
Here's what is in the summary report: http://prntscr.com/9q8rk5
Fyi, this is the link to the image I entered: https://usatftw.files.wordpress.com/2015/07/xxx_travel-kiawah-island-beach-17234_49734857.jpg?w=1000&h=600&crop=1

**Comment by davisagli** [comment]
The app doesn't know whether the URL that's entered is a direct link to an image, or a page that contains an image. So it guesses based on whether the URL ends with a common image extension like jpg/gif/png. And the URL you tested with doesn't meet that test because of the extra parameters.

It wouldn't be hard to take off the query string before checking for image extensions, if you want.

**Comment by davisagli** [comment]
It now will ignore any query string when checking for an image extension.
